language: java
sudo: false
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
script:
  - ./gradlew jacocoTestReport test

  after_success:
  # report coverage
  - bash <(curl -s https://codecov.io/bash)
