language: java
sudo: false
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

if: (type = pull_request AND repo = pusher/pusher-websocket-java) OR (branch = master)

script:
  - ./gradlew test
